<?php

namespace RCV\Core\Console\Commands\Docs;

use Illuminate\Console\Command;

class GenerateDocs extends Command
{
    protected $signature = 'module:docs {--output=docs}';
    protected $description = 'Generate basic module documentation stubs';

    public function handle(): int
    {
        $output = base_path($this->option('output'));
        if (!is_dir($output)) {
            mkdir($output, 0777, true);
        }
        file_put_contents($output.'/README.md', "# Module Documentation\n\nGenerated by module:docs\n");
        $this->info("Documentation generated at {$output}");
        return self::SUCCESS;
    }
}


